/*
 * LVX ISA support for gem5.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * DRAFT (Phase 1) — foundational header, not yet compile-verified.
 */

#ifndef __ARCH_LVX_REGS_MISC_HH__
#define __ARCH_LVX_REGS_MISC_HH__

#include "arch/lvx/lvx_registers.h"
#include "cpu/reg_class.hh"
#include "debug/LvxRegs.hh"

namespace gem5
{
namespace LvxISA
{

namespace misc_reg
{

// The LVX Special Function Registers (SFRs). In the MDS behavior these are the
// SRS storage, addressed by number (e.g. the generated RET reads SFR #3 = $ra).
// We model the whole SFR address space as one MiscRegClass and let the shim map
// readFromStorage_SRS/_SFR -> read/setMiscReg.
//
// PC and NPC are *Control* storage in the behavior, not SFRs -- the shim maps
// readFromStorage_PC / writeToStorage_NPC onto the gem5 PCState, not here. That
// is why SFR index 0 ($s0 = the PC) is an exception the shim resolves through
// the generated regfile_map.inc rather than reading misc-reg 0.
//
// The numbering, the field offsets and the size of the space are all facts of
// the ISA description, so they are NOT written here: lvx_registers.h is
// generated by MDS/BE/LIBC/BIN/libc-registers.pl and installed into this tree.
// These names are the ones this port actually uses; the header has ~2400 more.
// (This closes the placeholder-numbering TODO that stood here: only RA had ever
// been confirmed, and RA and CS turned out to be unused besides.)
enum : RegIndex
{
    PS = LVX_SFR_PS, // $s1 processor status  (bitfield; SE mode models PS.HLE only)
    LS = LVX_SFR_LS, // $s7 hardware-loop start PC   (LOOPDO)
    LE = LVX_SFR_LE, // $s8 hardware-loop end PC     (LOOPDO)
    LC = LVX_SFR_LC, // $s9 hardware-loop iteration count (LOOPDO)

    // The whole SFR address space, not just the named registers: most indices
    // are unnamed. Was hand-set to 256, which is half of it.
    NumRegs = LVX_SFR_COUNT
};

// Processor Status (PS) is a bitfield *Control* storage in the MDS behavior,
// not an SFR. SE-mode user code observes almost none of it, but PS.HLE (bit 5,
// hardware-loop enable) gates LOOPDO: with it clear the instruction throws an
// OPCODE trap. We model SE mode as "hardware loops always enabled" — HLE set,
// everything else zero. Both the PS-read shim (Layer B) and the bundle
// loop-back engine (Layer C) key off this single value.
namespace ps
{
enum : unsigned
{
    HLE_BIT = LVX_SFR_PS_HLE_SHIFT, // PS.HLE -- hardware-loop enable

    // PS.PL -- the protection ring the code is running in, PL0 the most
    // privileged (US11995218). SE mode leaves it at 0, so every system-register
    // ownership check passes; the check is still made (see shim.cc).
    PL_SHIFT = LVX_SFR_PS_PL_SHIFT,
    PL_WIDTH = LVX_SFR_PS_PL_WIDTH,
};

inline constexpr uint64_t SE_MODE_VALUE = (uint64_t{1} << HLE_BIT);

inline constexpr bool hwLoopEnabled() { return (SE_MODE_VALUE >> HLE_BIT) & 1; }

} // namespace ps

} // namespace misc_reg

inline constexpr RegClass miscRegClass(MiscRegClass, MiscRegClassName,
        misc_reg::NumRegs, debug::LvxRegs);

} // namespace LvxISA
} // namespace gem5

#endif // __ARCH_LVX_REGS_MISC_HH__
