# LVX ISA support for gem5 — CPU bindings (ArchISA/MMU/Interrupts/Decoder).
# SPDX-License-Identifier: BSD-3-Clause

from m5.objects.BaseAtomicSimpleCPU import BaseAtomicSimpleCPU
from m5.objects.BaseMinorCPU import (
    BaseMinorCPU,
    MinorFU,
    MinorFUPool,
    minorMakeOpClassSet,
)
from m5.objects.BaseNonCachingSimpleCPU import BaseNonCachingSimpleCPU
from m5.objects.BaseTimingSimpleCPU import BaseTimingSimpleCPU

# Pipeline stages generated by BE/GEM5 from Processor.table; a result written at
# stage S has dependence latency S - LVX_STAGE_RR.
from m5.objects.lvx_stages import (
    LVX_STAGE_E1,
    LVX_STAGE_E2,
    LVX_STAGE_E3,
    LVX_STAGE_E4,
    LVX_STAGE_RR,
    LVX_STAGE_SF,
    LVX_STAGE_SR,
)
from m5.objects.LvxDecoder import LvxDecoder
from m5.objects.LvxInterrupts import LvxInterrupts
from m5.objects.LvxISA import LvxISA
from m5.objects.LvxMMU import LvxMMU


class LvxCPU:
    ArchDecoder = LvxDecoder
    ArchMMU = LvxMMU
    ArchInterrupts = LvxInterrupts
    ArchISA = LvxISA


class LvxAtomicSimpleCPU(BaseAtomicSimpleCPU, LvxCPU):
    mmu = LvxMMU()


class LvxNonCachingSimpleCPU(BaseNonCachingSimpleCPU, LvxCPU):
    mmu = LvxMMU()


class LvxTimingSimpleCPU(BaseTimingSimpleCPU, LvxCPU):
    mmu = LvxMMU()


# Functional units as latency buckets, one per pipeline write stage: a result
# written at stage S has dependence latency S - LVX_STAGE_RR (lvx_stages.h), and
# LvxStaticInst routes each bundle to the FU whose opLat matches its (max) result
# latency, keyed by a bucket OpClass. Those OpClasses are routing labels, not
# semantics -- the per-opcode latency already separates e.g. FP16 (E3) from
# FP32/FP64 (E4) FADD/FMUL/FFMA. Resource hazards need no modelling (the
# assembler's bundling guarantees a valid bundle has none), so one lane per
# latency suffices; issueLat 1 keeps each lane pipelined (a bundle may issue
# every cycle), and srcRegsRelativeLats defaults to 0 so the RAW issue distance
# is exactly opLat = write stage - RR.
def _lvxFU(name, op_class, write_stage):
    return type(name, (MinorFU,), dict(
        opClasses=minorMakeOpClassSet([op_class]),
        opLat=write_stage - LVX_STAGE_RR,
        issueLat=1,
    ))()


class LvxFUPool(MinorFUPool):
    funcUnits = [
        _lvxFU("LvxFU_E1", "IntAlu",    LVX_STAGE_E1),
        _lvxFU("LvxFU_E2", "IntMult",   LVX_STAGE_E2),
        _lvxFU("LvxFU_E3", "FloatAdd",  LVX_STAGE_E3),
        _lvxFU("LvxFU_E4", "FloatMult", LVX_STAGE_E4),
        _lvxFU("LvxFU_SF", "FloatDiv",  LVX_STAGE_SF),
        _lvxFU("LvxFU_SR", "IntDiv",    LVX_STAGE_SR),
    ]


# In-order pipeline model. Consumes LvxStaticInst's src/dest register lists to
# stall a bundle until its sources are produced (RAW hazards) and applies the
# LvxFUPool latencies above -- the model that turns the dependency lists into
# cycle counts. LVX is a statically scheduled in-order VLIW, so an in-order
# pipeline is the right abstraction (one bundle issues per cycle unless stalled).
# See docs/register-buffer-deps.md.
class LvxMinorCPU(BaseMinorCPU, LvxCPU):
    mmu = LvxMMU()
    executeFuncUnits = LvxFUPool()
