/*
 * LVX ISA support for gem5 — Layer B shim: IEEE-754 floating-point helpers.
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (C) 2026 Liesme Tech.
 * Benoît Dupont de Dinechin (benoit.dinechin@gmail.com).
 *
 * Implements the f16/f32/f64 operator helpers the MDS-generated behavior bodies
 * call, backed by Berkeley SoftFloat (ext/softfloat, RISC-V specialization —
 * default-NaN, tininess-after-rounding, round-to-odd, and the RISC-V
 * out-of-range float->int saturation values). Per width W in {16,32,64}:
 *   arithmetic  fW_{add,sub,mul,mulAdd,mulnAdd,div,sqrt,rint}
 *   min/max     fW_{min,max,minNum,maxNum}
 *   compare     floatcomp_W  (eight ordered/unordered predicates)
 *   classify    fW_classify  (RISC-V FCLASS)
 *   conversions fW<->integer and the fW<->fW' widen/narrow pairs
 * The three widths are structurally identical (verified: same flag-binding order
 * and operand order per operation), so they are generated by width macros.
 *
 * All operators match RISC-V FP arithmetic exactly (mnemonics aside) -- any
 * divergence would be an LVX ISA spec bug. RISC-V has two min/max families and
 * so does LVX, with the plain/Num names inverted between them:
 *   LVX fW_minNum/fW_maxNum == RISC-V FMIN/FMAX  (IEEE minimumNumber/
 *       maximumNumber: return the numeric operand when one is NaN, canonical NaN
 *       only if both are, -0 < +0, invalid only on signaling NaN) == SoftFloat
 *       fW_min/fW_max.
 *   LVX fW_min/fW_max       == RISC-V FMINM/FMAXM (Zfa; IEEE minimum/maximum:
 *       NaN-PROPAGATING -- either operand NaN yields canonical NaN, still raising
 *       invalid on a signaling NaN).
 * fW_rint is fW_roundToInt with exact=true (RISC-V FROUNDNX: raises inexact).
 * Float->int saturates the RISC-V way (NaN/+ovf -> INT_MAX, -ovf -> INT_MIN;
 * unsigned NaN/+ovf -> UINT_MAX, negative -> 0). floatcomp threads no exception
 * flags (bare bool result, like the integer compares), so it raises no invalid
 * on a NaN -- a limitation of the helper signature, not the boolean result.
 *
 * These are PURE functions of (rounding mode, raw IEEE-754 bits). The generated
 * execute body owns all architectural FP state: it resolves the rounding mode
 * (static `floatmode`, or dynamic `$cs.RM` when floatmode==7), pre-applies the
 * `fnegate` sign flips, reads the current `$cs` sticky flags, ORs in this op's
 * freshly-raised flags, and writes `$cs` back. Each helper only sets SoftFloat's
 * rounding mode, clears the scratch flags, runs the op, and returns the result
 * plus this op's raised flags in the per-op Tuple's exact field order.
 *
 * Core-agnostic (shared by lvx_v1 and lvx_v2): FP semantics are identical across
 * cores (a shared-instruction difference would be an ISA authoring error), and
 * the helper ABI is verified byte-identical between the two cores' generated
 * glue. On lvx_v2 the packed/SIMD FP ops invoke these same scalar helpers.
 */
#include <cstdint>

extern "C" {
#include "softfloat.h"
}

// The flag-returning tuple POD types the generated behavior expects. Included the
// same way behavior.c does; identical across cores (verified), so core-agnostic.
#include "arch/lvx/generated/behavior_types.inc"

// int256_t — the widening (fW->fW') conversion helpers return a bare int256_t
// (not a flag tuple), matching their generated prototypes.
#include "arch/lvx/int256.h"

// SoftFloat internal fused multiply-add with an op selector (subProd negates the
// product). The public fW_mulAdd is this with op==0; FFMS needs -(a*b)+c, which
// is op==softfloat_mulAdd_subProd. Declared here to avoid pulling internals.h;
// the symbols are exported by libsoftfloat (s_mulAddF{16,32,64}.c).
extern "C" {
float16_t softfloat_mulAddF16(uint_fast16_t, uint_fast16_t, uint_fast16_t, uint_fast8_t);
float32_t softfloat_mulAddF32(uint_fast32_t, uint_fast32_t, uint_fast32_t, uint_fast8_t);
float64_t softfloat_mulAddF64(uint_fast64_t, uint_fast64_t, uint_fast64_t, uint_fast8_t);
}

namespace
{

// softfloat_mulAdd op selector for "subtract the product" (internals.h).
constexpr uint_fast8_t kMulAddSubProd = 2;

// LVX `floatmode` 3-bit code -> SoftFloat rounding mode.
//   0 RN nearest-even | 1 RZ toward-zero | 2 RD downward | 3 RU upward
//   4 RM nearest-max-magnitude | 5 reserved | 6 RO round-to-odd
// floatmode==7 ("use CS rounding") is resolved to a 0..6 code by the generated
// execute body, so the helper never sees it. The 6->odd(5) entry is why this is
// a table and not the identity.
inline uint_fast8_t
sfRoundingMode(uint8_t rm)
{
    static const uint8_t kMap[8] = {
        softfloat_round_near_even,    // 0 RN
        softfloat_round_minMag,       // 1 RZ
        softfloat_round_min,          // 2 RD
        softfloat_round_max,          // 3 RU
        softfloat_round_near_maxMag,  // 4 RM
        softfloat_round_near_even,    // 5 reserved (defensive)
        softfloat_round_odd,          // 6 RO
        softfloat_round_near_even,    // 7 dynamic (pre-resolved; unreachable)
    };
    return kMap[rm & 7];
}

// Set rounding mode + tininess and clear the scratch exception flags, once per
// helper call. Tininess-after-rounding is the RISC-V/LVX convention.
inline void
sfBegin(uint8_t rm)
{
    softfloat_roundingMode = sfRoundingMode(rm);
    softfloat_detectTininess = softfloat_tininess_afterRounding;
    softfloat_exceptionFlags = 0;
}

inline uint8_t flagIO() { return (softfloat_exceptionFlags & softfloat_flag_invalid)   ? 1 : 0; }
inline uint8_t flagDZ() { return (softfloat_exceptionFlags & softfloat_flag_infinite)  ? 1 : 0; }
inline uint8_t flagOV() { return (softfloat_exceptionFlags & softfloat_flag_overflow)  ? 1 : 0; }
inline uint8_t flagUN() { return (softfloat_exceptionFlags & softfloat_flag_underflow) ? 1 : 0; }
inline uint8_t flagIN() { return (softfloat_exceptionFlags & softfloat_flag_inexact)   ? 1 : 0; }

// Reinterpret the low bits of a raw operand as a SoftFloat float of each width.
inline float16_t fp16(uint64_t b) { return float16_t{(uint16_t)b}; }
inline float32_t fp32(uint64_t b) { return float32_t{(uint32_t)b}; }
inline float64_t fp64(uint64_t b) { return float64_t{(uint64_t)b}; }

// Raw-bits NaN tests and canonical quiet NaNs (RISC-V default NaN), per width,
// for the NaN-propagating min/max whose NaN handling is done outside SoftFloat.
inline bool isNaN16(uint16_t b){ return (b & 0x7C00) == 0x7C00 && (b & 0x03FF); }
inline bool isNaN32(uint32_t b){ return (b & 0x7F800000) == 0x7F800000 && (b & 0x007FFFFF); }
inline bool isNaN64(uint64_t b){ return (b & UINT64_C(0x7FF0000000000000)) == UINT64_C(0x7FF0000000000000)
                                     && (b & UINT64_C(0x000FFFFFFFFFFFFF)); }
constexpr uint16_t kDefaultNaN16 = 0x7E00;
constexpr uint32_t kDefaultNaN32 = 0x7FC00000;
constexpr uint64_t kDefaultNaN64 = UINT64_C(0x7FF8000000000000);

// floatcomp predicate: one of eight ordered/unordered predicates over the
// comparison of a and b (either NaN => unordered, else less/greater/equal, with
// +0.0 == -0.0). Matches the KVX reference and RISC-V compare results (OEQ =
// FEQ, OLT = FLT, OGE = a>=b i.e. FLE swapped; odd codes are the negations).
// Quiet compares -- a quiet NaN raises nothing, and no flag is threaded anyway.
#define FP_CMP_HELPER(W)                                                  \
inline bool lvxFloatcomp##W(uint8_t code, uint64_t a, uint64_t b)         \
{                                                                         \
    bool lt = f##W##_lt_quiet(fp##W(a), fp##W(b));                        \
    bool gt = f##W##_lt_quiet(fp##W(b), fp##W(a));                        \
    bool eq = f##W##_eq(fp##W(a), fp##W(b));                              \
    switch (code & 7) {                                                   \
      case 0:  return   lt || gt;    /* ONE ordered and not equal */      \
      case 1:  return !(lt || gt);   /* UEQ unordered or equal */         \
      case 2:  return   eq;          /* OEQ ordered and equal */          \
      case 3:  return  !eq;          /* UNE unordered or not equal */      \
      case 4:  return   lt;          /* OLT ordered and less than */       \
      case 5:  return  !lt;          /* UGE unordered or greater-or-eq */  \
      case 6:  return   gt || eq;    /* OGE ordered and greater-or-eq */   \
      default: return !(gt || eq);   /* ULT unordered or less than */      \
    }                                                                     \
}
FP_CMP_HELPER(16)
FP_CMP_HELPER(32)
FP_CMP_HELPER(64)

}  // namespace

// ---- Per-width operator helpers ---------------------------------------------
// add/sub -> {value, io, ov, in};  mul/mulAdd/mulnAdd -> {value, io, ov, un, in};
// div -> {value, io, dz, ov, un, in};  sqrt/rint -> {value, io, in};
// min/max/minNum/maxNum -> {value, io}. Flag order verified against the generated
// execute bodies for all three widths.
#define FP_ADDSUB(W, OP)                                                        \
Tuple_##W##_1_1_1                                                               \
Behavior_f##W##_##OP(void * /*self*/, uint8_t rm, uint64_t a, uint64_t b)       \
{                                                                              \
    sfBegin(rm);                                                               \
    float##W##_t r = f##W##_##OP(fp##W(a), fp##W(b));                          \
    return Tuple_##W##_1_1_1{ r.v, flagIO(), flagOV(), flagIN() };             \
}

#define FP_MUL(W)                                                              \
Tuple_##W##_1_1_1_1                                                            \
Behavior_f##W##_mul(void * /*self*/, uint8_t rm, uint64_t a, uint64_t b)       \
{                                                                              \
    sfBegin(rm);                                                               \
    float##W##_t r = f##W##_mul(fp##W(a), fp##W(b));                           \
    return Tuple_##W##_1_1_1_1{ r.v, flagIO(), flagOV(), flagUN(), flagIN() }; \
}

#define FP_MULADD(W)                                                                    \
Tuple_##W##_1_1_1_1                                                                     \
Behavior_f##W##_mulAdd(void * /*self*/, uint8_t rm, uint64_t a, uint64_t b, uint64_t c) \
{                                                                                      \
    sfBegin(rm);                                                                       \
    float##W##_t r = f##W##_mulAdd(fp##W(a), fp##W(b), fp##W(c));                       \
    return Tuple_##W##_1_1_1_1{ r.v, flagIO(), flagOV(), flagUN(), flagIN() };         \
}

// FFMS: fused -(a*b)+c (product subtracted from the accumulator). subProd negates
// the product's sign, matching "subtracted from %1".
#define FP_MULNADD(W, UT)                                                               \
Tuple_##W##_1_1_1_1                                                                     \
Behavior_f##W##_mulnAdd(void * /*self*/, uint8_t rm, uint64_t a, uint64_t b, uint64_t c)\
{                                                                                      \
    sfBegin(rm);                                                                       \
    float##W##_t r = softfloat_mulAddF##W((UT)a, (UT)b, (UT)c, kMulAddSubProd);         \
    return Tuple_##W##_1_1_1_1{ r.v, flagIO(), flagOV(), flagUN(), flagIN() };         \
}

#define FP_DIV(W)                                                                      \
Tuple_##W##_1_1_1_1_1                                                                   \
Behavior_f##W##_div(void * /*self*/, uint8_t rm, uint64_t a, uint64_t b)                \
{                                                                                      \
    sfBegin(rm);                                                                       \
    float##W##_t r = f##W##_div(fp##W(a), fp##W(b));                                    \
    return Tuple_##W##_1_1_1_1_1{ r.v, flagIO(), flagDZ(), flagOV(), flagUN(), flagIN() };\
}

#define FP_SQRT(W)                                                             \
Tuple_##W##_1_1                                                                \
Behavior_f##W##_sqrt(void * /*self*/, uint8_t rm, uint64_t a)                  \
{                                                                              \
    sfBegin(rm);                                                              \
    float##W##_t r = f##W##_sqrt(fp##W(a));                                    \
    return Tuple_##W##_1_1{ r.v, flagIO(), flagIN() };                        \
}

// RISC-V FROUNDNX: exact=true, so rounding raises inexact.
#define FP_RINT(W)                                                             \
Tuple_##W##_1_1                                                                \
Behavior_f##W##_rint(void * /*self*/, uint8_t rm, uint64_t a)                  \
{                                                                              \
    sfBegin(rm);                                                              \
    float##W##_t r = f##W##_roundToInt(fp##W(a), softfloat_roundingMode, true);\
    return Tuple_##W##_1_1{ r.v, flagIO(), flagIN() };                        \
}

// SoftFloat fW_min/fW_max are RISC-V FMIN/FMAX (minimumNumber/maximumNumber:
// signed-zero correct, invalid only on sNaN). LVX fW_minNum/fW_maxNum are those
// directly; LVX fW_min/fW_max are NaN-propagating (FMINM/FMAXM), the same but
// with the value overridden to canonical NaN when an input is NaN.
#define FP_MINMAX(W, UT)                                                        \
Tuple_##W##_1                                                                   \
Behavior_f##W##_minNum(void * /*self*/, uint64_t a, uint64_t b)                 \
{                                                                              \
    softfloat_exceptionFlags = 0;                                              \
    float##W##_t r = f##W##_min(fp##W(a), fp##W(b));                           \
    return Tuple_##W##_1{ r.v, flagIO() };                                     \
}                                                                              \
Tuple_##W##_1                                                                   \
Behavior_f##W##_maxNum(void * /*self*/, uint64_t a, uint64_t b)                 \
{                                                                              \
    softfloat_exceptionFlags = 0;                                              \
    float##W##_t r = f##W##_max(fp##W(a), fp##W(b));                           \
    return Tuple_##W##_1{ r.v, flagIO() };                                     \
}                                                                              \
Tuple_##W##_1                                                                   \
Behavior_f##W##_min(void * /*self*/, uint64_t a, uint64_t b)                    \
{                                                                              \
    softfloat_exceptionFlags = 0;                                              \
    float##W##_t r = f##W##_min(fp##W(a), fp##W(b));                           \
    UT v = (isNaN##W((UT)a) || isNaN##W((UT)b)) ? kDefaultNaN##W : r.v;         \
    return Tuple_##W##_1{ v, flagIO() };                                       \
}                                                                              \
Tuple_##W##_1                                                                   \
Behavior_f##W##_max(void * /*self*/, uint64_t a, uint64_t b)                    \
{                                                                              \
    softfloat_exceptionFlags = 0;                                              \
    float##W##_t r = f##W##_max(fp##W(a), fp##W(b));                           \
    UT v = (isNaN##W((UT)a) || isNaN##W((UT)b)) ? kDefaultNaN##W : r.v;         \
    return Tuple_##W##_1{ v, flagIO() };                                       \
}

// FCOMPD/W/H: boolean predicate; no exception flags threaded.
#define FP_COMPARE(W)                                                           \
bool                                                                            \
Behavior_floatcomp_##W(void * /*self*/, uint8_t code, uint64_t a, uint64_t b)   \
{                                                                              \
    softfloat_exceptionFlags = 0;                                              \
    return lvxFloatcomp##W(code, a, b);                                        \
}

// FCLASS: RISC-V classification bitmask.
#define FP_CLASSIFY(W)                                                         \
int256_t                                                                       \
Behavior_f##W##_classify(void * /*self*/, uint64_t a)                          \
{                                                                              \
    return int256_fromUInt64(f##W##_classify(fp##W(a)));                       \
}

// float -> integer (RISC-V FCVT.{i,u}{32,64}.{f}): round per rm, exact=true;
// out-of-range/NaN saturate the RISC-V way (values from the specialization).
// SW = source float width, DW = dest int width, SIGN = i|ui, RT = SoftFloat ret.
#define FP_TO_INT(SW, DW, SIGN, RT)                                            \
Tuple_##DW##_1_1                                                               \
Behavior_f##SW##_to_##SIGN##DW(void * /*self*/, uint8_t rm, uint64_t a)        \
{                                                                              \
    softfloat_exceptionFlags = 0;                                             \
    RT r = f##SW##_to_##SIGN##DW(fp##SW(a), sfRoundingMode(rm), true);         \
    return Tuple_##DW##_1_1{ (uint##DW##_t)r, flagIO(), flagIN() };            \
}

// integer -> float (RISC-V FCVT.f.{i,u}{32,64}): 32-bit sources are exact,
// 64-bit sources round per rm; never invalid. AT = signed/unsigned arg cast.
#define INT_TO_FP(SIGN, SW, DW, AT)                                            \
Tuple_##DW##_1_1                                                               \
Behavior_##SIGN##SW##_to_f##DW(void * /*self*/, uint8_t rm, uint64_t a)        \
{                                                                              \
    sfBegin(rm);                                                              \
    float##DW##_t r = SIGN##SW##_to_f##DW((AT)a);                             \
    return Tuple_##DW##_1_1{ r.v, flagIO(), flagIN() };                       \
}

// float -> narrower float (RISC-V FCVT.f'.f): round per rm; io/ov/un/in.
#define FP_NARROW(SW, DW)                                                          \
Tuple_##DW##_1_1_1_1                                                               \
Behavior_f##SW##_to_f##DW(void * /*self*/, uint8_t rm, uint##SW##_t a)             \
{                                                                                 \
    sfBegin(rm);                                                                  \
    float##DW##_t r = f##SW##_to_f##DW(float##SW##_t{a});                          \
    return Tuple_##DW##_1_1_1_1{ r.v, flagIO(), flagOV(), flagUN(), flagIN() };    \
}

// float -> wider float (RISC-V FCVT.f'.f): exact widening; canonicalizes NaN.
// The generated prototype returns a bare int256_t (no rm, no flag tuple).
#define FP_WIDEN(SW, DW)                                                       \
int256_t                                                                       \
Behavior_f##SW##_to_f##DW(void * /*self*/, uint##SW##_t a)                     \
{                                                                              \
    float##DW##_t r = f##SW##_to_f##DW(float##SW##_t{a});                      \
    return int256_fromUInt64(r.v);                                            \
}

extern "C" {

// Arithmetic, min/max, compare, classify — all three widths.
FP_ADDSUB(16, add)  FP_ADDSUB(16, sub)
FP_ADDSUB(32, add)  FP_ADDSUB(32, sub)
FP_ADDSUB(64, add)  FP_ADDSUB(64, sub)
FP_MUL(16)  FP_MUL(32)  FP_MUL(64)
FP_MULADD(16)  FP_MULADD(32)  FP_MULADD(64)
FP_MULNADD(16, uint16_t)  FP_MULNADD(32, uint32_t)  FP_MULNADD(64, uint64_t)
FP_DIV(16)  FP_DIV(32)  FP_DIV(64)
FP_SQRT(16)  FP_SQRT(32)  FP_SQRT(64)
FP_RINT(16)  FP_RINT(32)  FP_RINT(64)
FP_MINMAX(16, uint16_t)  FP_MINMAX(32, uint32_t)  FP_MINMAX(64, uint64_t)
FP_COMPARE(16)  FP_COMPARE(32)  FP_COMPARE(64)
FP_CLASSIFY(16)  FP_CLASSIFY(32)  FP_CLASSIFY(64)

// f64 <-> integer.
FP_TO_INT(64, 32, i, int_fast32_t)   FP_TO_INT(64, 32, ui, uint_fast32_t)
FP_TO_INT(64, 64, i, int_fast64_t)   FP_TO_INT(64, 64, ui, uint_fast64_t)
INT_TO_FP(i, 32, 64, int32_t)   INT_TO_FP(ui, 32, 64, uint32_t)
INT_TO_FP(i, 64, 64, int64_t)   INT_TO_FP(ui, 64, 64, uint64_t)

// f32 <-> integer.
FP_TO_INT(32, 32, i, int_fast32_t)   FP_TO_INT(32, 32, ui, uint_fast32_t)
FP_TO_INT(32, 64, i, int_fast64_t)   FP_TO_INT(32, 64, ui, uint_fast64_t)
INT_TO_FP(i, 32, 32, int32_t)   INT_TO_FP(ui, 32, 32, uint32_t)
INT_TO_FP(i, 64, 32, int64_t)   INT_TO_FP(ui, 64, 32, uint64_t)

// float <-> float widen/narrow: f16<->f32, f32<->f64.
FP_WIDEN(16, 32)   FP_NARROW(32, 16)
FP_WIDEN(32, 64)   FP_NARROW(64, 32)

}  // extern "C"
