#!/usr/bin/env bash
#
# The decoder must accept a bundle of up to LVX_MAXBUNDLEWORDS syllables, and
# must not quietly invent a bundle boundary when it runs out of room.
#
# MaxBundleSyllables (src/arch/lvx/types.hh) was 16, derived by hand from "2
# each of BCU/ALU/LSU/EXT instructions plus up to 8 IMMX" -- correct for eight
# issue slots, but LVX has ten (BCU0 BCU1 ALU0 ALU1 LSU0 LSU1 EXT0..EXT3), so
# the bound is 10 + 8 = 18.  Worse than being two short, moreBytes() responded
# to the cap by ending the bundle *while the parallel bit still said more
# syllables followed*, so the remainder decoded as a fresh bundle: a 17- or
# 18-syllable bundle executed as two, costing an extra issue and an extra
# cycle, with exit code 0 and no diagnostic anywhere.  On an instrument whose
# purpose is counting cycles that is the worst available failure mode.
#
# WHAT IS MEASURED.  gem5's simInsts counts one *bundle* as one "instruction"
# on this VLIW, so it is exactly the quantity the bug moved: a bundle wrongly
# split in two shows up as +1.  The test therefore asserts that 16, 17 and 18
# syllables all cost the SAME number of bundles.
#
# HOW THE BUNDLES ARE BUILT.  gas will not emit one: its resource table binds
# well before the syllable count does, and the largest bundle it will assemble
# is 15 syllables (4x `addd' with a 64-bit immediate = 4 TINY + 8 IMMX, 2x
# `xcopyo' until AUXW's availability of 2 stops it, plus one BCU).  So the
# words are taken from `addd $rN = $rN, <imm64>' -- three syllables each,
# opcode + 2 IMMX -- assembled one bundle at a time, and spliced by setting the
# parallel bit on every word but the last.  The result over-subscribes TINY and
# IMMX and is not a legal bundle; that is deliberate and irrelevant, because
# the question here is only what the DECODER does with a given syllable count.
# Steering drops the instructions it has no slot for, so the register results
# are not checked and must not be.
#
# Env: LVX_TOOLCHAIN_BIN  GEM5  LVX_CPU(atomic|timing|minor)
#
set -u
here="$(cd "$(dirname "$0")" && pwd)"
gem5root="$(cd "$here/../../.." && pwd)"

BIN="${LVX_TOOLCHAIN_BIN:-$gem5root/../lvx-toolchain/bin}"
GEM5="${GEM5:-$gem5root/build/LVX/gem5.opt}"
RUNCFG="$gem5root/tests/lvx/run_lvx.py"
LDS="${LVX_LDSCRIPTS:-$gem5root/../lvx-newlib/libgloss/lvx-mbr/linker_scripts}"
export LVX_CPU="${LVX_CPU:-atomic}"

for tool in "$BIN/lvx-mbr-gcc" "$BIN/lvx-mbr-as" "$BIN/lvx-mbr-objcopy" \
            "$GEM5" "$RUNCFG"; do
    [ -e "$tool" ] || { echo "missing: $tool"; exit 2; }
done

work="$(mktemp -d)"; trap 'rm -rf "$work"' EXIT

# --- the word pool: eight `addd' with 64-bit immediates, 24 syllables ----------
{   printf '\t.text\n\t.globl t\nt:\n'
    for i in $(seq 0 7); do
        printf '\taddd $r%d = $r%d, 0x11223344556677%02x\n\t;;\n' \
               $((20 + i)) $((20 + i)) $((0x88 + i))
    done
} > "$work/pool.s"
"$BIN/lvx-mbr-as" --march lvx-2 -o "$work/pool.o" "$work/pool.s" || {
    echo "bundle-syllables   FAIL (pool assemble)"; exit 2; }
"$BIN/lvx-mbr-objcopy" -O binary --only-section=.text "$work/pool.o" \
                       "$work/pool.bin" || {
    echo "bundle-syllables   FAIL (pool objcopy)"; exit 2; }

# splice <nwords> <break-at|-> <out.c>
#   Sets the parallel bit on every word but the last, so the words form ONE
#   bundle.  With a break-at index, that word's parallel bit is cleared too,
#   making two bundles -- the negative control.
splice() {
    python3 - "$work/pool.bin" "$1" "$2" "$3" <<'PY'
import struct, sys
raw = open(sys.argv[1], "rb").read()
n, brk, out = int(sys.argv[2]), sys.argv[3], sys.argv[4]
w = list(struct.unpack("<%dI" % (len(raw) // 4), raw))[:n]
if len(w) < n:
    sys.exit("pool too small: %d words for %d" % (len(w), n))
w = [x | 0x80000000 for x in w]
w[n - 1] &= 0x7fffffff
if brk != "-":
    w[int(brk)] &= 0x7fffffff
body = "\n".join('"\\t.word 0x%08x\\n"' % x for x in w)
open(out, "w").write(
    '/* generated by check_bundle_syllables.sh -- %d syllables, break=%s */\n'
    'extern void t (void);\n__asm__ (\n"\\t.text\\n"\n"\\t.globl t\\n"\n"t:\\n"\n'
    '%s\n"\\tret\\n"\n"\\t;;\\n"\n);\n'
    'int main (void) { t (); return 0; }\n' % (n, brk, body))
PY
}

# bundles <name> -> prints simInsts, or "panic", or "fail"
bundles() {
    local name=$1
    if ! "$BIN/lvx-mbr-gcc" -O0 -march=lvx-1 -T lvx-sim.ld -L "$LDS" \
             "$work/$name.c" -o "$work/$name.elf" > "$work/$name.build" 2>&1; then
        echo fail; return
    fi
    if timeout 300 "$GEM5" --outdir="$work/m5-$name" "$RUNCFG" \
            "$work/$name.elf" < /dev/null > "$work/$name.out" \
            2> "$work/$name.err"; then
        awk '$1=="simInsts"{print $2}' "$work/m5-$name/stats.txt"
    elif grep -q 'MaxBundleSyllables' "$work/$name.err"; then
        echo panic
    else
        echo fail
    fi
}

rc=0
for n in 16 17 18 19; do splice $n - "$work/b$n.c" || exit 2; done
splice 18 14 "$work/bsplit.c" || exit 2

base=$(bundles b16)
case "$base" in
  ''|fail|panic) echo "bundle-syllables   FAIL (the 16-syllable baseline did not run: $base)"
                 exit 2 ;;
esac
echo "16-syllables       PASS (baseline: $base bundles)"

for n in 17 18; do
    got=$(bundles "b$n")
    if [ "$got" = "$base" ]; then
        echo "$n-syllables       PASS (one bundle, $got)"
    elif [ "$got" = panic ]; then
        echo "$n-syllables       FAIL (panicked: the cap is below LVX_MAXBUNDLEWORDS)"; rc=1
    elif [ "$got" = fail ]; then
        echo "$n-syllables       FAIL (did not run)"; rc=1
    else
        echo "$n-syllables       FAIL (split into two bundles: $got vs $base)"; rc=1
    fi
done

# --- negative control ---------------------------------------------------------
# A test whose expectation cannot fail is worth nothing.  simInsts has to be
# able to SEE a second bundle, or the three PASSes above would also pass on an
# ISS that counted nothing.  Same 18 words, parallel bit cleared at word 14, so
# they are genuinely two bundles: the count must go up by exactly one.
got=$(bundles bsplit)
if [ "$got" = "$((base + 1))" ]; then
    echo "negative-ctrl      PASS (a real split reads as $got, base+1)"
elif [ "$got" = "$base" ]; then
    echo "negative-ctrl      FAIL (simInsts cannot distinguish one bundle from"
    echo "                         two -- the checks above prove nothing)"; rc=1
else
    echo "negative-ctrl      FAIL (expected $((base + 1)), got $got)"; rc=1
fi

# --- past the architectural maximum -------------------------------------------
# 19 syllables is not an LVX bundle at all, so the fetched words are a bad
# branch target or data.  Truncating silently is what the old decoder did; the
# only honest answer is to stop and name the address.
got=$(bundles b19)
if [ "$got" = panic ]; then
    echo "19-syllables       PASS (panics rather than truncating)"
elif [ "$got" = fail ]; then
    echo "19-syllables       FAIL (did not run, and did not panic)"; rc=1
else
    echo "19-syllables       FAIL (accepted $got bundles for an impossible"
    echo "                         bundle -- silent truncation is back)"; rc=1
fi

[ $rc -eq 0 ] && echo "bundle-syllables   ALL PASS"
exit $rc
